// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/html dojo/_base/array dojo/Deferred dojo/promise/all dojo/request jimu/utils".split(" "),function(l,k,m,h,n,p,q,g){return l(null,{appConfig:void 0,currentStyleName:void 0,currentLayoutName:void 0,_manifest:void 0,constructor:function(b){this._manifest=b;this.domNodes={}},clear:function(){var b;this.appConfig=null;for(b=0;b<this._manifest.layouts.length;b++)if("appLayout"===this._manifest.layouts[b].name){this._manifest.layouts[b].domNode&&m.destroy(this._manifest.layouts[b].domNode);
this._manifest.layouts.splice(b,1);break}},loadLayouts:function(){var b=new n,c=[],a=h.filter(this._manifest.layouts,function(a){return"appLayout"!==a.name});h.forEach(a,function(a){c.push(q(this._manifest.url+a.uri,{handleAs:"json"}))},this);p(c).then(k.hitch(this,function(e){var c;h.forEach(a,function(a,b){a.layoutConfig=e[b];if("default"===a.name)c=a.layoutConfig;else{var d=a.layoutConfig.layoutDefinition;a.layoutConfig=g.mixinAppConfigPosition(c,a.layoutConfig);a.layoutConfig.layoutDefinition=
d}a.layoutConfig.mobileLayout&&(a.layoutConfig.mobileLayout=g.mixinAppConfigPosition(a.layoutConfig,a.layoutConfig.mobileLayout),delete a.layoutConfig.mobileLayout.mobileLayout)},this);b.resolve()}),function(){b.reject()});return b},_processLayoutConfig:function(b,c){return g.mixinAppConfigPosition(b,c)},setAppConfig:function(b){this.appConfig=b},getName:function(){return this._manifest.name},getVersion:function(){return this._manifest.version},getLabel:function(){return this._manifest.label},getIcon:function(){return this._manifest.icon},
getLayouts:function(){return this._manifest.layouts},getStyles:function(){return this._manifest.styles},getUrl:function(){return this._manifest.url},getCurrentStyle:function(){return this.getStyleByName(this.currentStyleName)},getCurrentLayout:function(){return this.getLayoutByName(this.currentLayoutName)},changeCurrentStyle:function(b){this.currentStyleName=b},changeCurrentLayout:function(b){this.currentLayoutName=b},addLayout:function(b,c,a,e){var f,d=this.getLayouts();for(f=0;f<d.length;f++)if(d[f].name===
b)return null;b={description:"this is current app layout",name:b,label:e,layoutConfig:c,domClass:a};this._manifest.layouts.push(b);return b},getStyleByName:function(b){var c,a=null;for(c=0;c<this._manifest.styles.length;c++)if(this._manifest.styles[c].name===b){a=this._manifest.styles[c];break}return a},getLayoutByName:function(b){var c,a=null;for(c=0;c<this._manifest.layouts.length;c++)if(this._manifest.layouts[c].name===b){a=this._manifest.layouts[c];break}return a},getLayoutByAppConfig:function(b){var c,
a=null;for(c=0;c<this._manifest.layouts.length;c++)if(this.isAppUseLayout(b,this._manifest.layouts[c].layoutConfig)){a=this._manifest.layouts[c];break}return a},isAppUseLayout:function(b,c){var a=k.clone(b),e=k.clone(c);a.map||(a.map={});e.map||(e.map=a.map);a.map.position||(a.map.position={left:0,top:0});e.map.position||(e.map.position=a.map.position);if(!g.isEqual(a.layoutDefinition,e.layoutDefinition)||!g.isEqual(a.map.position,e.map.position))return!1;a.widgetOnScreen||(a.widgetOnScreen={});e.widgetOnScreen||
(e.widgetOnScreen={});a.widgetOnScreen.widgets||(a.widgetOnScreen.widgets=[]);e.widgetOnScreen.widgets||(e.widgetOnScreen.widgets=[]);a.widgetOnScreen.groups||(a.widgetOnScreen.groups=[]);e.widgetOnScreen.groups||(e.widgetOnScreen.groups=[]);var f,d;f=a.widgetOnScreen.widgets.length<e.widgetOnScreen.widgets.length?a.widgetOnScreen.widgets.length:e.widgetOnScreen.widgets.length;for(d=0;d<f;d++)if(a.widgetOnScreen.widgets[d].position||(a.widgetOnScreen.widgets[d].position={}),e.widgetOnScreen.widgets[d].position||
(e.widgetOnScreen.widgets[d].position=a.widgetOnScreen.widgets[d].position),e.widgetOnScreen.widgets[d].position.relativeTo||(e.widgetOnScreen.widgets[d].position.relativeTo=a.widgetOnScreen.widgets[d].position.relativeTo),!g.isEqual(a.widgetOnScreen.widgets[d].position,e.widgetOnScreen.widgets[d].position))return!1;f=a.widgetOnScreen.groups.length<e.widgetOnScreen.groups.length?a.widgetOnScreen.groups.length:e.widgetOnScreen.groups.length;for(d=0;d<f;d++)if(a.widgetOnScreen.groups[d].panel||(a.widgetOnScreen.groups[d].panel=
{}),e.widgetOnScreen.groups[d].panel||(e.widgetOnScreen.groups[d].panel=a.widgetOnScreen.groups[d].panel),a.widgetOnScreen.groups[d].panel.position||(a.widgetOnScreen.groups[d].panel.position={}),e.widgetOnScreen.groups[d].panel.position||(e.widgetOnScreen.groups[d].panel.position=a.widgetOnScreen.groups[d].panel.position),e.widgetOnScreen.groups[d].panel.position.relativeTo||(e.widgetOnScreen.groups[d].panel.position.relativeTo=a.widgetOnScreen.groups[d].panel.position.relativeTo),!g.isEqual(a.widgetOnScreen.groups[d].panel.position,
e.widgetOnScreen.groups[d].panel.position))return!1;return!0},getLayoutFromConfig:function(b){var c={};b=k.clone(b);b.widgetOnScreen&&(c.widgetOnScreen={},b.widgetOnScreen.widgets&&(c.widgetOnScreen.widgets=[],h.forEach(b.widgetOnScreen.widgets,function(a,b){c.widgetOnScreen.widgets[b]={position:a.position?a.position:{left:0,top:0}}})),b.widgetOnScreen.groups&&(c.widgetOnScreen.groups=[],h.forEach(b.widgetOnScreen.groups,function(a,b){c.widgetOnScreen.groups[b]={position:a.position?a.position:{left:0,
top:0}}})));b.map&&(c.map={position:b.map.position});return c}})});