// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:builder/plugins/widget-config/WidgetChoosePage.html":'\x3cdiv class\x3d"widget-choose-page"\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"officialSection" class\x3d"official-section"\x3e\r\n    \x3cdiv class\x3d"section search" data-dojo-attach-point\x3d"searchSectionNode"\x3e\r\n      \x3cdiv data-dojo-attach-point\x3d"searchInputNode"\x3e\x3c/div\x3e\r\n      \x3cdiv class\x3d"list widget-list" data-dojo-attach-point\x3d"widgetListNode"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"customSection" class\x3d"custom-section"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"customSearchInputNode"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/html dojo/_base/array dojo/topic dojo/on dojo/Deferred dojo/promise/all dojo/query dojo/NodeList-dom dijit/_WidgetBase dijit/_TemplatedMixin dojo/text!./WidgetChoosePage.html jimu/dijit/Search jimu/WidgetManager jimu/dijit/LoadingShelter jimu/dijit/Message jimu/dijit/TabContainer3 jimu/utils jimu/portalUtils jimu/portalUrlUtils builder/serviceUtils esri/lang ./CustomWidgets".split(" "),function(t,e,d,f,u,g,m,n,p,C,v,w,x,q,y,z,k,A,h,D,E,l,B,r){return t([v,
w],{templateString:x,showCustomWidgets:!1,postMixInProperties:function(){this.widgetManager=y.getInstance()},startup:function(){this.inherited(arguments);this.showCustomWidgets||d.addClass(this.domNode,"hide-custom-widgets");this.tab=new A({tabs:[{title:this.nls.officialWidgets,content:this.officialSection},{title:this.nls.customWidgets,content:this.customSection}]});this.tab.placeAt(this.domNode);this.searchDijit1=new q({placeholder:this.nls.widgetSearchHint,onSearch:e.hitch(this,this._onFilterDefaultWidget),
searchWhenInput:!0},this.searchInputNode);this._getWidgets();this.own(g(window,"resize",e.hitch(this,this.resize)));setTimeout(e.hitch(this,function(){this.resize()}),100);this.loading=new z({hidden:!0});this.loading.placeAt(this.domNode);this.loading.startup();this.showCustomWidgets&&(this.searchDijit2=new q({placeholder:this.nls.widgetSearchHint,onChange:e.hitch(this,this._onFilterCustomWidget),onSearch:e.hitch(this,this._onSearchCustomWidget),searchWhenInput:!1},this.customSearchInputNode),this.allCustomWidgets=
new r({portalUrl:window.portalUrl,fromNode:this.fromNode}),this.allCustomWidgets.placeAt(this.customSection),this.filterCustomWidgets=new r({portalUrl:window.portalUrl,hidden:!0,fromNode:this.fromNode}),this.filterCustomWidgets.placeAt(this.customSection),this.own(g(this.tab,"tabChanged",e.hitch(this,function(a){a!==this.nls.customWidgets||this.allCustomWidgets.queried||(this.allCustomWidgets.queried=!0,this.allCustomWidgets.queryItems())}))))},_onFilterCustomWidget:function(a){this.allCustomWidgets.show();
this.filterCustomWidgets.hide();a?this.allCustomWidgets.filterLocally(function(b){return b.title&&0<=b.title.toUpperCase().indexOf(a.toUpperCase())}):this.allCustomWidgets.filterLocally(function(){return!0})},_onSearchCustomWidget:function(a){a?(this.allCustomWidgets.hide(),this.filterCustomWidgets.show(),this.filterCustomWidgets.queryItems({q:'title:"'+a+'"'})):(this.allCustomWidgets.show(),this.filterCustomWidgets.hide())},_onFilterDefaultWidget:function(a){var b;b=""===a?this.allWidgets:f.filter(this.allWidgets,
function(b){if(-1<b.label.toUpperCase().indexOf(a.toUpperCase()))return!0});this._createWidgetNodes(b)},resize:function(){var a=d.getContentBox(this.domNode).h,b=a-60;d.setStyle(this.searchSectionNode,{height:a+"px"});d.setStyle(this.widgetListNode,{height:b+"px"})},setAppConfig:function(a){this.appConfig=a},_getWidgets:function(){var a={};this.appConfig.map["2D"]&&(a.support2D=!0);this.appConfig.map["3D"]&&(a.support3D=!0);this.appConfig.map["2D"]&&this.appConfig.map["3D"]&&(a.support2D=!0,a.support3D=
!0);a.platform=window.stemappInfo.appType;this.options.includeOffPanel||(a["properties.inPanel"]=!0);l.searchWidgets(a).then(e.hitch(this,function(a){a.success?(this.allWidgets=this._filterSingletonWidgets(a.widgets),this._createWidgetNodes(this.allWidgets)):console.log(a.message)}))},_filterSingletonWidgets:function(a){return f.filter(a,function(a){return!1===a.properties.supportMultiInstance&&this._checkWidgetIsInAppConfig(this.appConfig,a.name)?!1:!0},this)},_checkWidgetIsInAppConfig:function(a,
b){var c=[];0===h.getControllerWidgets(a).length?a.visitElement(e.hitch(this,function(a){a.isOnScreen&&a.name===b&&c.push(a)})):c=a.getConfigElementsByName(b);return 0<c.length},_createWidgetNodes:function(a){d.empty(this.widgetListNode);f.forEach(a,function(a){this._createWidgetNode(a)},this)},_createWidgetNode:function(a){var b,c;b=d.create("div",{"class":"widget-node","data-widget-name":a.name},this.widgetListNode);c=d.create("div",{"class":"box"},b);d.create("div",{"class":"box-selected"},b);
d.create("img",{"class":"icon",src:a.icon},c);d.create("div",{"class":"label",innerHTML:h.stripHTML(a.label),title:a.label},b);b.setting={name:a.name,label:a.label,version:a.version,closeable:"removeableWidgetOnScreen"===this.fromList?!0:void 0};h.widgetJson.addManifest2WidgetJson(b.setting,a);b.setting.uri=a.amdFolder+"Widget";b.box=c;this.own(g(b,"click",e.hitch(this,this._onWidgetClick,b)));return b},_onWidgetClick:function(a){this._isMultipleSelection()?d.hasClass(a,"jimu-state-selected")?d.removeClass(a,
"jimu-state-selected"):d.addClass(a,"jimu-state-selected"):(p(".jimu-state-selected",this.domNode).removeClass("jimu-state-selected"),d.addClass(a,"jimu-state-selected"))},_isMultipleSelection:function(){var a=this.fromNode;return"addBtn"===a.type&&"poolWidgets"===this.fromList||"addBtn"===a.type&&"groupOnScreen"===this.fromList&&this._canAddMoreWidgetsInGroup(a.gnode)||"group"===a.type&&this._canAddMoreWidgetsInGroup(a)},_canAddMoreWidgetsInGroup:function(a){return a?"undefined"===typeof a.setting.maxWidgets||
a.setting.maxWidgets>a.setting.widgets.length+1:!1},onOk:function(){(0===this.tab.getSelectedIndex()?this._getOfficialSelection():this._getCustomSelection()).then(e.hitch(this,function(a){var b=[];"group"===this.fromNode.type&&"undefined"!==typeof this.fromNode.setting.maxWidgets&&this.fromNode.setting.widgets.length+a.length>this.fromNode.setting.maxWidgets?(new k({message:B.substitute({maxCount:this.fromNode.setting.maxWidgets},this.nls.addWidgetExceedMax)}),this.loading.hide()):(f.forEach(a,function(a){b.push(this._copyWidget(a))},
this),n(b).then(e.hitch(this,function(b){var c;for(c=0;c<b.length;c++)if(!b[c].success){new k({message:b[c].message});this.loading.hide();return}this.loading.hide();u.publish("widgetChoosePageOk",a,this.fromNode);this.popup.close()})))}),function(a){console.error(a.stack)})},_getOfficialSelection:function(){var a=new m,b=p(".jimu-state-selected",this.domNode);if(0===b.length)return new k({message:this.nls.emptyMessage}),a.reject({message:this.nls.emptyMessage}),a;this.loading.show();b=f.map(b,function(a){return e.clone(a.setting)});
a.resolve(b);return a},_getCustomSelection:function(){var a=[],a=this.allCustomWidgets.isVisible()?this.allCustomWidgets.getSelectedWidgetItems():this.filterCustomWidgets.getSelectedWidgetItems();return n(a.map(function(a){return l.getManifestFromItem(a).then(function(b){var c={name:b.name,label:a.title,version:b.version};h.widgetJson.addManifest2WidgetJson(c,b);c.uri=h.widgetJson.getUriFromItem(a);c.itemId=a.id;return c})}))},_copyWidget:function(a){var b=0,c,d=[],f=h.getControllerWidgets(this.appConfig);
this.appConfig.visitElement(e.hitch(this,function(c){if(0!==f.length||c.isOnScreen)c.name===a.name&&b++,d.push(c.label)}));a.icon=a.manifest.folderUrl+"images/icon.png?wab_dv\x3d"+window.deployVersion;if(0===b)a.label=a.label,c=l.copyWidgetToApp(window.appInfo.id,a);else if(0<b){c=new m;for(var g=a.label+"_"+(b+1);-1<d.indexOf(g);)b++,g=a.label+"_"+(b+1);a.label=g;c.resolve({success:!0})}return c}})});