// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/array dojo/_base/lang dojo/_base/html dojo/Evented dojo/on dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin jimu/dijit/CheckBox".split(" "),function(b,f,c,d,g,h,k,l,m){b=b([k,l,m,g],{baseClass:"map-proxy-item",templateString:'\x3cdiv class\x3d"row"\x3e\x3cdiv data-dojo-attach-point\x3d"layerTitle" class\x3d"col" title\x3d"${title}"\x3e${title}\x3c/div\x3e\x3cdiv data-dojo-attach-point\x3d"consumeCreditsContent" class\x3d"col credits-value"\x3e\x3c/div\x3e\x3cdiv class\x3d"use-proxy col" data-dojo-attach-point\x3d"useProxyCheckBox" data-dojo-type\x3d"jimu/dijit/CheckBox"\x3e\x3c/div\x3e\x3cdiv data-dojo-attach-point\x3d"loading" class\x3d"loading-content"\x3e\x3c/div\x3e\x3c/div\x3e',
appProxyManager:null,sourceUrl:"",title:"",useProxy:!1,proxyUrl:"",proxyId:"",premium:!0,consumeCredits:!1,postCreate:function(){this.inherited(arguments);!0===this.consumeCredits&&d.addClass(this.consumeCreditsContent,"credits");d.setStyle(this.loading,"display","none");this.useProxyCheckBox.setStatus(!0);!0===this.useProxy&&this.proxyId&&this.proxyUrl?this.useProxyCheckBox.setValue(!0):this.useProxyCheckBox.setValue(!1);this.own(h(this.useProxyCheckBox,"change",c.hitch(this,this._onUseProxyChange)))},
_onUseProxyChange:function(a){a&&!this.proxyId&&this._createProxy();!a&&this.proxyId&&this._deleteProxy()},_createProxy:function(){this._startProcess("Create Proxy");if(this.appProxyManager){var a=!1;this.appProxyManager.proxies&&0<this.appProxyManager.proxies.length&&(a=f.some(this.appProxyManager.proxies,function(a){return a.sourceUrl===this.sourceUrl&&a.proxyId&&a.proxyUrl}));if(a)this._checkCreateProxiesCallback(this.appProxyManager.proxies);else try{this.appProxyManager.createProxies([{sourceUrl:this.sourceUrl}]).then(c.hitch(this,
this._checkCreateProxiesCallback),c.hitch(this,this._createProxiesFail))}catch(e){this._createProxiesFail(e.message)}}else this.emit("processError",this.nls.deleteProxyFailed+" "+this.sourceUrl),this._stopProcess("appProxyManager is undefined",!1)},_checkCreateProxiesCallback:function(a){f.some(a,c.hitch(this,function(a){if(a.sourceUrl===this.sourceUrl)return this.proxyUrl=a.proxyUrl,this.proxyId=a.proxyId,this.useProxy=!0}))?(this.emit("proxyCreated",{sourceUrl:this.sourceUrl,proxyUrl:this.proxyUrl,
proxyId:this.proxyId,title:this.title,useProxy:!0}),this._stopProcess("Create Proxy",!0)):(this.emit("processError",this.nls.createProxyFailed+" "+this.sourceUrl),this._stopProcess("Create Proxy",!1))},_createProxiesFail:function(a){this.proxyUrl=this.proxyId="";this.useProxy=!1;this.emit("processError",this.nls.createProxyFailed+" "+this.sourceUrl);this._stopProcess(a||"Create Proxy",!1)},_deleteProxy:function(){var a=this.proxyId;this.proxyId=this.proxyUrl="";this.useProxy=!1;this.emit("proxyDeleted",
{sourceUrl:this.sourceUrl,useProxy:!1});this.useProxyCheckBox.setValue(!1);if(this.appProxyManager)try{this.appProxyManager.deleteProxies([{proxyId:a}])}catch(e){console.error(e)}},_startProcess:function(a){d.setStyle(this.loading,"display","");this.useProxyCheckBox.setStatus(!1);this.emit("processStart",a)},_stopProcess:function(a,b){d.setStyle(this.loading,"display","none");this.useProxyCheckBox.setStatus(!0);"undefined"!==typeof b&&this.useProxyCheckBox.setValue(b);this.emit("processEnd",a)}});
b.PROXY_CREATED="proxyCreated";b.PROXY_DELETED="proxyDeleted";b.PROCESS_START="processStart";b.PROCESS_END="processEnd";b.PROCESS_ERROR="processError";return b});